In [30]:
import numpy as np
import pandas as pd

# Jupyter Notebook의 출력을 소수점 이하 3자리로 제한
%precision %.3f
# Dataframe의 출력을 소수점 이하 3자리로 제한
pd.set_option('display.precision', 3)

In [31]:
df = pd.read_csv('../data/ch2_scores_em.csv',
                 index_col='student number')
# df의 처음 5행을 표시
df.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [32]:
df.shape

(50, 2)

In [33]:
# 해당 데이터를 NumPy로 계산하기 위해, NumPy의 array구조로 된 scores라는 이름으로 저장
scores = np.array(df['english'])[:10]
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [34]:
scores_df = pd.DataFrame({'score':scores},
                         index=pd.Index(['A', 'B', 'C', 'D', 'E',
                                         'F', 'G', 'H', 'I', 'J'],
                                        name='student'))
scores_df

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

In [35]:
sum(scores) / len(scores)

55.000

In [36]:
np.mean(scores)

55.000

In [37]:
scores_df.mean()

score    55.0
dtype: float64

In [38]:
sorted_scores = np.sort(scores)
sorted_scores

array([41, 42, 48, 49, 56, 57, 58, 65, 65, 69], dtype=int64)

In [39]:
n = len(sorted_scores)
if n % 2 == 0:
    m0 = sorted_scores[n//2 - 1]
    m1 = sorted_scores[n//2]
    median = (m0 + m1) / 2
else:
    median = sorted_scores[(n+1)//2 - 1]
median

56.500

In [40]:
np.median(scores)

56.500

In [41]:
scores_df.median()

score    56.5
dtype: float64

In [42]:
pd.Series([1, 1, 1, 2, 2, 3]).mode() # 최빈값

0    1
dtype: int64

In [43]:
mean = np.mean(scores)
deviation = scores - mean
deviation

array([-13.,  14.,   1., -14.,   2.,  -7.,  10.,  -6.,  10.,   3.])

In [44]:
np.mean(deviation ** 2)

86.000

In [45]:
np.var(scores)

86.000

In [47]:
summary_df = scores_df.copy()
summary_df['deviation'] = deviation
summary_df

score  deviation
student                  
A           42      -13.0
B           69       14.0
C           56        1.0
D           41      -14.0
E           57        2.0
F           48       -7.0
G           65       10.0
H           49       -6.0
I           65       10.0
J           58        3.0

In [48]:
summary_df['square of deviation'] = np.square(deviation)
summary_df

score  deviation  square of deviation
student                                       
A           42      -13.0                169.0
B           69       14.0                196.0
C           56        1.0                  1.0
D           41      -14.0                196.0
E           57        2.0                  4.0
F           48       -7.0                 49.0
G           65       10.0                100.0
H           49       -6.0                 36.0
I           65       10.0                100.0
J           58        3.0                  9.0

In [49]:
summary_df.mean()

score                  55.0
deviation               0.0
square of deviation    86.0
dtype: float64

In [50]:
np.sqrt(np.var(scores, ddof=0))

9.274

In [51]:
np.std(scores, ddof=0)

9.274

In [52]:
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [53]:
np.sqrt(scores)

array([6.481, 8.307, 7.483, 6.403, 7.55 , 6.928, 8.062, 7.   , 8.062,
       7.616])

In [54]:
np.max(scores) - np.min(scores)

28

In [55]:
scores_Q1 = np.percentile(scores, 25)
scores_Q3 = np.percentile(scores, 75)
scores_IQR = scores_Q3 - scores_Q1
scores_IQR

15.000

In [56]:
pd.Series(scores).describe()

count    10.000
mean     55.000
std       9.775
min      41.000
25%      48.250
50%      56.500
75%      63.250
max      69.000
dtype: float64

In [69]:
a=np.array([1,2,4,3,5])

In [70]:
np.mean(a)

3.000

In [71]:
np.sort(a)

array([1, 2, 3, 4, 5])

In [72]:
np.median(a)

3.000

In [73]:
np.var(a)

2.000

In [74]:
np.square(a)

array([ 1,  4, 16,  9, 25])

In [75]:
np.sqrt(a)

array([1.   , 1.414, 2.   , 1.732, 2.236])

In [76]:
np.std(a)

1.414

In [77]:
np.std(a, ddof=0)

1.414

In [78]:
np.max(a)

5

In [79]:
np.min(a)

1

In [80]:
np.percentile(a, 25)

2.000